### ISSUE TITLE
Module on the Activity-feed page with UserId exposed filters items

### ISSUE THREAD

**Issue by ergodaveh** [DNNCommunity/DNN.Blog#115]
Whenever the Blog module is present on the Activity-Feed page the module shows items authored with the same userId  
...is there any oppurtunity 'option' to ignore the UserId

**Comment by valadas** [comment]
I can confirm that the blog module reatcs to both author=xx and to userid=xx

I am also afraid that modifying this behaviour may cause problems to some templates or customizations on sites that link to the module using userid.

But I found a workaround, assuming you have a manageable amount of users, you can go to their profile and set a vanity url, that way their activity feed will have a url that does not have the userid in the parameters. I think this would solve the issue.
