### ISSUE TITLE
When Image is uploaded onto blog it adds a grey border on the left or right

### ISSUE THREAD

**Issue by rogerg1967** [DNNCommunity/DNN.Blog#118]
Hello,

there is an issue with the upload. We think it's got something to do with the aspect ratio.
We are using the newest version of blog module.

If we try uploading a png file it adds a black background onto the image if it's jpg it add border on the left or top, that is definitely not part of the image before the upload....

Could someone please help? 

is there a way to change the aspect ratio? What should it be?

**Comment by WHairstonLOI** [comment]
This may be due to the template you've selected to display your blog. Please see my discussion in Issue #100 of the issues I encountered with oversized images. It may be possible that you can simply change the template files on your site to get the behavior you need.

**Comment by rogerg1967** [comment]
Thank you, that helped

**Comment by valadas** [comment]
I am closing since I don't think there is anything here to fix on the module. If that is not the case please open a new issue with a link where we can see the problem.
