### ISSUE TITLE
Copy Module doesn't work on DNN9

### ISSUE THREAD

**Issue by rogerg1967** [DNNCommunity/DNN.Blog#121]
Hello we have several websites using dnn 9 and there are functionalities that are required to have on these websites, for instance blog list...

However, we are not able to add any of these.

I am able to click on the button which says 'Copy Module' and then select the template, but it does not add any module copies on the page...

Is there a fix for that?
Is it a different issue?

**Comment by rogerg1967** [comment]
Any updates on this?

**Comment by WHairstonLOI** [comment]
After some testing on my DNN9 site, I'm seeing the same behavior. It appears that it's impossible to perform either the Copy Module function, or to simply add a new Blog module. The "floating box" indicating the module appears on the screen, but it can't be dragged to any of the panes to be dropped on the page.

**Comment by rogerg1967** [comment]
I am able to add module the first time but not the copies...  for us not even a floating box appear.... When I click the button "Copy Module" it gives a popup with the options for copying the module, then when I click "Add" it just does nothing at all.... The floating box does not appear... The page does not reload....

So I thought maybe if I manually refresh the page, maybe the module will on there, because in the options for copying the module, one of them was the pane, but no.... that didn't work.

Would there be more updates on this?

**Comment by WHairstonLOI** [comment]
On my site, if I try to do either of the following, I simply can’t place the module on the page:

1.	On a page WITHOUT a blog module, enter Edit mode, choose “Add New Module” and select the Blog. A floating “Blog” box appears in the center of the screen (as it does for most modules), but the box can’t be dragged into any of the panes. The HTML module (for example) can be dragged/placed without issue on this same site.
2.	On a page with an EXISTING blog module, login as a user with Blog management rights, click the “Copy Module” button in the upper left corner of the Blog module, and similar behavior will occur.

I directly e-mailed some of the contributors to this project on Monday (I couldn't see any direct contact info for "donker", who is listed as the project owner). One responded asking for more information (basically what I just posted above) and stating that he would test, but I don't know if anyone has actually begun working on a fix yet. I certainly hope someone can fix this soon, as I'm delaying the DNN9 upgrade for a few sites until this gets resolved.

**Comment by valadas** [comment]
I can reproduce but it is a duplicated of #98  so I am closing this one to keep the older reported one, please read the workaround in the other issue if you need a solution in the meantime.
