### ISSUE TITLE
RESX:WrittenBy.Text

### ISSUE THREAD

**Issue by Forro-54** [DNNCommunity/DNN.Blog#128]
Hi,
I have installed the version 6.04.01 of the module on a fresh install of DNN 08.00.04 (226) and I am getting RESX:WrittenBy.Text
where certain heading should be.

![resex-error](https://user-images.githubusercontent.com/7608527/36637517-945cdb08-1a31-11e8-9b00-086e61398591.jpg)

The image above shows the error I am talking about.
I have had this error popup before on error releases of the blog module.
By the way this is a development site so I have time to try and work it out.

Any help appreciated.
Kind Regards
Trevor

**Comment by Forro-54** [comment]
Please disregard this post.
It appears the problem is with DNN itself.
If you have seen this in DNN please let me know and in the meantime I will post the problem on DNN forum.

Thanks in Advance
Trevor

**Comment by valadas** [comment]
Closing since OP indicated to disregard this issue
