### ISSUE TITLE
No Install Zip

### ISSUE THREAD

**Issue by IrishChieftain** [DNNCommunity/DNN.Blog#136]
## Please summarize your question in one sentence
Where is the install zip? 

## Give a more extended description
I downloaded the project and it doesn't even compile in VS 2015.

Error	BC30002	Type 'Global.DotNetNuke.Web.UI.WebControls.DnnGrid' is not defined.	DotNetNuke.Modules.Blog	C:\Development\DNN.Blog-development\Manage.ascx.designer.vb

UPDATE
I copied DLLs for broken references into my bin folder: DotNetNuke.Web.Deprecated and SharpZipLib. Got project to compile in release mode but no install folder is being created?

**Comment by EPTamminga** [comment]
You will find the install in the releases tab of the repository.
https://github.com/DNNCommunity/DNN.Blog/releases

**Comment by IrishChieftain** [comment]
Thanks! :)
