### ISSUE TITLE
Categories not being added

### ISSUE THREAD

**Issue by hacqua** [DNNCommunity/DNN.Blog#143]
I've done a clean install of the blog on DNN 9.1, configured a single blog module and I'm trying to create a few categories. I can enter the new categories, one per line, but the "Add" button does not do anything. Tried to close everything and start again many times but categories are never saved.

**Comment by parasdaryanani** [comment]
I've got the exact same issue. @hacqua have you found a solution since then?

**Comment by parasdaryanani** [comment]
This is a duplicate issue. Refer to #122.

**Comment by valadas** [comment]
I am closing this one in favor of #122
