### ISSUE TITLE
Critical SQL syntax errors prevents installation and upgrade

### ISSUE THREAD

**Issue by stephen-lim** [DNNCommunity/DNN.Blog#165]
## Describe the bug
We encountered SQL syntax errors during the upgrade from an old DNN 7 blog to the latest Blog 6.4.2 version.

## To Reproduce
Upgrade to the latest blog. First error is encountered as described below. After we corrected the line 184 (see explanation below), we encountered a second SQL error.

The only way to successfully upgrade is to correct the syntax error in Blog_06.00.02_Install.zip package and perform a 2-step upgrade. After upgrading to 6.0.2, perform the remaining upgrade to Blog_6.4.2_Install.zip

Please note, correcting the first syntax error in Blog_6.4.2_Install.zip will still encounter the 2nd error below.

## Error log
**First error:**

Info Start Sql execution: 04.00.00.SqlDataProvider file
Exceptions: System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near '('. ...
ALTER TABLE dbo.[Blog_Entry_Tags] ADD CONSTRAINT FK_Blog_Entry_Tags_Tags FOREIGN KEY ( [TagID] ) REFERENCES dbo.Blog_Tags ( [TagID] ) ON DELETE CASCADEWITH (ALLOW_PAGE_LOCKS=OFF) ON UPDATE CASCADE

**Second error:**

Info Start Sql execution: 06.00.01.SqlDataProvider file
Cannot insert duplicate key row in object 'dbo.ModuleDefinitions' with unique index 'IX_ModuleDefinitions'. ...
UPDATE dbo.ModuleDefinitions SET DefinitionName='DNNBlog.Blog' FROM dbo.ModuleDefinitions md INNER JOIN dbo.DesktopModules dm ON dm.DesktopModuleID=md.DesktopModuleID WHERE md.DefinitionName='Blog' AND dm.ModuleName='Blog'

## Additional context
The syntax problem is due to line 184. Notice the word **CASCADEWITH (ALLOW_PAGE_LOCKS=OFF)** should have been **CASCADE** only.

```
ALTER TABLE {databaseOwner}[{objectQualifier}Blog_Entry_Tags]  
	ADD  CONSTRAINT FK_{objectQualifier}Blog_Entry_Tags_Tags FOREIGN KEY ( [TagID] ) REFERENCES {databaseOwner}{objectQualifier}Blog_Tags ( [TagID] ) 
		ON DELETE CASCADEWITH (ALLOW_PAGE_LOCKS=OFF)
		ON UPDATE CASCADE
```

**Comment by jncraig** [comment]
Is there any chance that you have the TurboScripts installed?

**Comment by stephen-lim** [comment]
No, we don't have the TurboScripts. The first error is an obvious syntax error. The 2nd error is likely either a race condition/logic error as it tries to rename the module definition names because the new Blog v6 has been re-architectured using a different set of modules.

**Comment by jncraig** [comment]
Which version of DNN are you using?  The release notes for Blog 6.2.0 say "Dependency moved up to DNN 7.1.2" so it seems that you need to DNN 7.1.2 installed.

**Comment by stephen-lim** [comment]
We were running the latest DNN 9.6.1 before upgrading the Blog so this issue is very much relevant.
