### ISSUE TITLE
Posting to Blog from Word 365

### ISSUE THREAD

**Issue by CubeDweller** [DNNCommunity/DNN.Blog#176]
Hi. 

Our techs have been using Word to post outages to our Intranet blog module.
But we just went to Word 365 and it no longer works. 
It seems like its connecting as I can see existing entries but can edit or publish.

Is there some trick I know not of?

On DNN 8.0.4 and Blog 4.1.1
If I need to upgrade the module to get it to work, what version for DNN 8?

Thanks, CD

**Comment by CubeDweller** [comment]
Ok. So far no clue why Word 365 won't publish to the Blog.

On my DEV server, Tried upgrading the Blog Module to just about every offered version (even tried fresh installs), Every upgrade/install outright fails or installs then has DNNgrid errors, Variety of error messages too numerous to list, but all are mentioned on this forum or at the dnncommunity with no solutions.

So far the only solution seems to be **stay with** 4.1.1 and use Open Live Writer instead of Word.
https://openlivewriter.com/

**Comment by slaterjsharp** [comment]
Hi CD, not sure where I saw this, but you need to update your site first for this module to work. DNN 9.8.0 is where you want to be, as that finally boots out Telerik. Also, I would say that your text needs to make a stop in notepad or similar plain text editor to get rid of the MS "cruft" that their version of XML spits out. Or stick with Open Live Writer, as that may have cleaner output. Hope that helped.

**Comment by hismightiness** [comment]
I had no idea people could use Word to create new blog posts.  That's pretty cool, but I'd suggest moving on to Open Live Writer instead.  It's closer to a native experience and removes some of the fluff that could get in the way in the Word user interface.

**Comment by CubeDweller** [comment]
Thanks Everyone!
slaterjsharp - That's good info. It will be awhile before we do any big upgrades. So we are stuck were we are at "for now".
hismightiness - Always great to hear from you!

Years ago I was tasked with "Make it so our support Techs can post outages to the Intranet remotely (without going there or needing to be trained as editors). So the Blog module and the publish from Word fit the bill perfectly; well until our last Office upgrade. 
So we are all using "Open Live Writer" now. And it has been working fine. Thank goodness.
The DNN Community ROCKS!
