### ISSUE TITLE
Errors wtih version 06.05.00

### ISSUE THREAD

**Issue by slaterjsharp** [DNNCommunity/DNN.Blog#179]
## Describe the bug
Blog module is not showing entries after upgrading DNN and blog module versions. Admin functions not working.

## Software Versions
- DNN: 09.08.00
- Blog Module: 06.05.00

## To Reproduce
1. At our test site, <redacted>, blog entries are not showing up.
2. Additionally, on the Manage Blogs we can only look at the first page of listings.  If we hit any of the page numbers at the bottom we get Service not Available
3. Screen captures are below
4. Error log from time of these captures is also attached. Snippet of error: DotNetNuke.Framework.PageBase - An error has occurred while loading page.
System.Web.HttpException (0x80004005): The GridView 'grdPosts' fired event PageIndexChanging which wasn't handled.

## Expected behavior
Need to view existing blog entries after upgrade. Need to view all entries as an admin on the Manage Blog screens. 

## Screenshots
<screen shots redacted>

## Error log
Error log posted, was collected during the error generations above

<log redacted>

## Additional context
<info redacted>

**Comment by slaterjsharp** [comment]
Sorry about that, issue was internal to our process. Testing server... miconfigured, for lack of a better word. Redacted certain info, will also be redacting in edits. Apologies for distraction.

**Comment by hismightiness** [comment]
Thank you for updating this issue and letting us know. :)
