### ISSUE TITLE
Add Canonical Tag to the Page Header

### ISSUE THREAD

**Issue by hismightiness** [DNNCommunity/DNN.Blog#180]
## Is your feature request related to a problem?
When you review reports of a website using this module, the pages with this module on it get dinged by SEO tools like Moz.com for not having a canonical tag on pages it has access to. Have a canonical tag even on pages that you know won't have duplicate content still improves your search results ranking by Google and other search engines.

## Describe the solution you'd like
All public views should inject a canonical tag into the page header.

## Describe alternatives you've considered
N/A

## Additional context

![image](https://user-images.githubusercontent.com/938023/106937549-bde50400-66d2-11eb-902d-f314b9b0fe83.png)

**Comment by Andy9999** [comment]
This would be a great SEO enhancement!
