### ISSUE TITLE
DNN CE v8.0.4.226 - Blog Installation Error

### ISSUE THREAD

**Issue by JaySMa** [DNNCommunity/DNN.Blog#83]
Got to the point of finishing up the update and deleting files, and received an error.

From Event Logs:
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:e1182913-05c1-4ed9-a9f0-f84d21585581
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:JZjh8BCQjuK3iHlRQ7I0gQ==
Message:FileSystemEntryType not matched!
StackTrace:
   at SchwabenCode.QuickIO.QuickIOFile.InternalFileExists(String uncPath)
   at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFiles(Array arrPaths)
   at DotNetNuke.Services.Installer.Installers.CleanupInstaller.ProcessCleanupFile()
InnerMessage:
InnerStackTrace:
Source:SchwabenCode.QuickIO
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:

**Comment by marklxndr** [comment]
Did you ever get a resolution? I'm having the same issue. I think my log is exactly the same:

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:2ba077f6-be16-478b-96ec-7cf41e07e8fb
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:JZjh8BCQjuK3iHlRQ7I0gQ==
Message:FileSystemEntryType not matched!
StackTrace:
   at SchwabenCode.QuickIO.QuickIOFile.InternalFileExists(String uncPath)
   at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFiles(Array arrPaths)
   at DotNetNuke.Services.Installer.Installers.CleanupInstaller.ProcessCleanupFile()
InnerMessage:
InnerStackTrace:
Source:SchwabenCode.QuickIO
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:

**Comment by wwwizard59** [comment]
I also got to the all the way to the "clean up" point ...
I used blog version 06.04.00

Install Package::DNN_Blog
Info::Starting Installation
Info::Starting Installation - DotNetNuke.Blog
Info::Starting Installation - Script
Info::Begin Sql execution
Info::Creating backup of previous version - Install.06.00.00.SqlDataProvider
Info::Created - Install.06.00.00.SqlDataProvider
Info::Executing Install.06.00.00.SqlDataProvider
Info::Start Sql execution: Install.06.00.00.SqlDataProvider file
Info::End Sql execution: Install.06.00.00.SqlDataProvider file
Info::Creating backup of previous version - 06.00.01.SqlDataProvider
Info::Created - 06.00.01.SqlDataProvider
Info::Executing 06.00.01.SqlDataProvider
Info::Start Sql execution: 06.00.01.SqlDataProvider file
Info::End Sql execution: 06.00.01.SqlDataProvider file
Info::Creating backup of previous version - 06.00.05.SqlDataProvider
Info::Created - 06.00.05.SqlDataProvider
Info::Executing 06.00.05.SqlDataProvider
Info::Start Sql execution: 06.00.05.SqlDataProvider file
Info::End Sql execution: 06.00.05.SqlDataProvider file
Info::Creating backup of previous version - 06.00.07.SqlDataProvider
Info::Created - 06.00.07.SqlDataProvider
Info::Executing 06.00.07.SqlDataProvider
Info::Start Sql execution: 06.00.07.SqlDataProvider file
Info::End Sql execution: 06.00.07.SqlDataProvider file
Info::Creating backup of previous version - 06.00.08.SqlDataProvider
Info::Created - 06.00.08.SqlDataProvider
Info::Executing 06.00.08.SqlDataProvider
Info::Start Sql execution: 06.00.08.SqlDataProvider file
Info::End Sql execution: 06.00.08.SqlDataProvider file
Info::Creating backup of previous version - 06.02.00.SqlDataProvider
Info::Created - 06.02.00.SqlDataProvider
Info::Executing 06.02.00.SqlDataProvider
Info::Start Sql execution: 06.02.00.SqlDataProvider file
Info::End Sql execution: 06.02.00.SqlDataProvider file
Info::Creating backup of previous version - 06.04.00.SqlDataProvider
Info::Created - 06.04.00.SqlDataProvider
Info::Executing 06.04.00.SqlDataProvider
Info::Start Sql execution: 06.04.00.SqlDataProvider file
Info::End Sql execution: 06.04.00.SqlDataProvider file
Info::Creating backup of previous version - Uninstall.SqlDataProvider
Info::Created - Uninstall.SqlDataProvider
Info::Finished Sql execution
Info::Component installed successfully - Script
Info::Starting Installation - Assembly
Info::Assembly registered - bin\DotNetNuke.Modules.Blog.dll
Info::Creating backup of previous version - bin\DotNetNuke.Modules.Blog.dll
Info::Created - bin\DotNetNuke.Modules.Blog.dll
Info::Assembly registered - bin\CookComputing.XmlRpcV2.dll
Info::Creating backup of previous version - bin\CookComputing.XmlRpcV2.dll
Info::Created - bin\CookComputing.XmlRpcV2.dll
Info::Binding redirect added for assembly - bin\CookComputing.XmlRpcV2.dll
Info::Component installed successfully - Assembly
Info::Starting Installation - Cleanup
Info::Processing Cleanup File - 6.0.0
Info::ExceptionSchwabenCode.QuickIO.UnmatchedFileSystemEntryTypeException: FileSystemEntryType not matched! at SchwabenCode.QuickIO.QuickIOFile.InternalFileExists(String uncPath) at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFiles(Array arrPaths) at DotNetNuke.Services.Installer.Installers.CleanupInstaller.ProcessCleanupFile()
Info::Installation Failed - Cleanup
Info::Rolling back component install - Script
Info::Restored backup of previous version - 06.00.01.SqlDataProvider
Info::Restored backup of previous version - 06.00.05.SqlDataProvider
Info::Restored backup of previous version - 06.00.07.SqlDataProvider
Info::Restored backup of previous version - 06.00.08.SqlDataProvider
Info::Restored backup of previous version - 06.02.00.SqlDataProvider
Info::Restored backup of previous version - 06.04.00.SqlDataProvider
Info::Restored backup of previous version - Install.06.00.00.SqlDataProvider
Info::Restored backup of previous version - Uninstall.SqlDataProvider
Info::Component rolled back successfully - Script
Info::Rolling back component install - Assembly
Info::Restored backup of previous version - bin\DotNetNuke.Modules.Blog.dll
Info::Restored backup of previous version - bin\CookComputing.XmlRpcV2.dll
Info::Component rolled back successfully - Assembly
Info::Installation Failed - DotNetNuke.Blog
Info::Deleted temporary install folder
Info::Installation Failed

**Comment by valadas** [comment]
This is actually a Dnn bug that was resolved in Dnn 9.2.2 so I will close this issue since it was fixed in Dnn, see https://github.com/dnnsoftware/Dnn.Platform/pull/2207 for reference.
