### ISSUE TITLE
WLW cannot connect

### ISSUE THREAD

**Issue by hooligannes** [DNNCommunity/DNN.Blog#84]
DNN 8.0.3 and Blog 6.4.0
Using http://mysite/Blog.aspx and the link obtained from the module I try to connect. I get a "500 Internal Server Error" reply. WLW could connect back in DNN 7.

**Comment by valadas** [comment]
Windows Live Writer was discontinued but they have made it Open source as Open Live Writer available at: http://openlivewriter.org/

Following the instructions at
https://github.com/DNNCommunity/DNN.Blog/blob/development/_Documentation/Manual.md#wlw
worked for me.

@hooligannes If you can reproduce using the new software and latest blog module release, please reopen a new issue.
