### ISSUE TITLE
latest posts URLs not localized

### ISSUE THREAD

**Issue by fprati** [DNNCommunity/DNN.Blog#90]
Version 6.4.0 does not resolve issue #59: [post:parenturl] still sends it to the default language page instead of the current language page. Am I making a mistake with the tamplate? Here is what I am using:

<div class="blog_post">
 <div class="blog_post_title">
  <a href="[post:parenturl]">[post:localizedtitle]</a>
 </div>
 <div class="blog_post_details">
  [Post:PublishedOnDate|d]
 </div>
</div>

See http://www.energolux-gdfsuez.lu/de/startseite: latest news links send visitors to the FR pages.

**Comment by fprati** [comment]
`<div class="blog_post">
 <div class="blog_post_title">
  <a href="[post:parenturl]">[post:localizedtitle]</a>
 </div>
 <div class="blog_post_details">
  [Post:PublishedOnDate|d]
 </div>
</div>`

**Comment by valadas** [comment]
I cannot reproduce using latest release.

If you can still reproduce the issue using the latest version, please open a new issue and include steps to reproduce the issue such as the template used, how localization and urls for localization is setup, etc.
