### ISSUE TITLE
RESX:ControlTitle_postedit.Text

### ISSUE THREAD

**Issue by Forro-54** [DNNCommunity/DNN.Blog#91]
Hi, I have just upgraded a dev site to dnn8.0.3 and DNN Blog to 6.4.0 and have a question.

When I start a new post the words  RESX:ControlTitle_postedit.Text is visible above the editor.

![blog630error](https://cloud.githubusercontent.com/assets/7608527/20511733/bb2e5c5c-b0ce-11e6-8a9d-d588abfb8ca6.jpg)

Is this OK or not

Kind Regards
Trevor

An update to issue:
I have setup 4 test sites with dnn 8.4 on 2 different severs.
This problem has raised it head on different servers both with a new virgin intall of dnn.
![resx](https://cloud.githubusercontent.com/assets/7608527/20754889/108e6c76-b761-11e6-93a7-411f04e208c4.jpg)

A further update on this issue:
I installed and created 2 more websites(fresh install of DNN8.4) and this problem has appeared on another site:

![resx2](https://cloud.githubusercontent.com/assets/7608527/20782045/35e37e46-b7dc-11e6-9c0f-dbe6bcf3a4c3.jpg)

Than means the problem is showing in 50% of cases

**Comment by valadas** [comment]
I cannot reproduce using latest version, please upgrade the module and if you can still reproduce, please open a new issue. This usually happens when a resource file is missing. If it is still the case, also let us know if the site uses more than the default language.
