### ISSUE TITLE
DNN Blog Upgrade Path?

### ISSUE THREAD

**Issue by carizzio** [DNNCommunity/DNN.Blog#93]
I have a site that is currently running DNN Framework 6.2.8 and DNN Blog module version 4.1.1.  I want to upgrade to DNN 9.0 but I am afraid that I will need to upgrade the DNN Blog module in order to successfully complete the upgrade to DNN 9.0.  I see that the current release of DNN Blog is 6.4.0 but I cannot find documentation that outlines the upgrade path for the module or DNN Core version requirements for the various versions of DNN Blog.

I am doing testing on a "clone" of the live site and I have been able to successfully upgrade to DNN 7.1.2.  However, multiple attempts at upgrading from 7.1.2 to 7.4.2 have failed.  I am following an upgrade path of 6.2.8 -> 6.2.9 -> 7.1.2 -> 7.4.2 -> 8.0.4 -> 9.0.0 which I found at evotiva.com.

Any assistance would be greatly appreciated.

Chuck R.

**Comment by valadas** [comment]
Blog 06.02.00 should work from Dnn 7.1.2 up to Dnn 9.1.1
Blog 06.04.01 should work from Dnn 8.0.0 up to Dnn 9.3.x(upcoming) and/or more

I am closing this issue, but if you have problems following this upgrade path, feel free to open a new issue with the details (Dnn and module version, error logs, etc.)
