### ISSUE TITLE
Adding Blog Module multiple times to page(s), no option to select blog.

### ISSUE THREAD

**Issue by cmariotti** [DNNCommunity/DNN.Blog#94]
I am using DNN v9 (also happened on v8)...
If I create a blog and make an entry.
I have one page dedicated to the blog... another (say Home)...
If I add multiple Blog items (say Search, Calendar and v60) and delete or remove them or move them around... eventually, it seems to forget that it has a Blog to display... if I change the Blog Settings so that I can select the blog, there are no blogs to choose from. Basically, I have a page and module display the blog, but other displays on other pages no longer have the option to select that blog to display... It's basically as if it doesn't think it has any active blogs.

**Comment by valadas** [comment]
I cannot reproduce using latest version, if you still have that problem after upgrading to the latest version, please open an new issue with steps to reproduce.
