### ISSUE TITLE
When I click on the blog overview to expand the post, throws a 404

### ISSUE THREAD

**Issue by suttyct** [DNNCommunity/DNN.Blog#95]
Hi When I click on the blog overview to expand the post, throws a 404, from what I can see is that it adds the name of the post to the end of the URL and this causes the crash, if I change the end post name to Default.aspx it works fine. 
redirect URL that doesn't work:
http://www.mysite.co.za/COFNEWS/tabid/220/Post/2797/Jacket-Chapter-16
Below is the link that works if I manually edit the end and change it with Default.aspx
http://www.mysite.co.za/COFNEWS/tabid/220/Post/2797/Default.aspx

**Comment by valadas** [comment]
I cannot reproduce using the latest version of the blog module.

If this is still a problem after upgrading to latest versions, please open a new issues with following info:
- What do your urls looks like on other pages, are you using advanced urls, do other pages need the .aspx entension to work?
